<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [3]:
x = 10
assert x >= 0, "x is becoming negative!"

In [4]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [8]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.5
The square of 5 is 25!


In [6]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.haha
Oh oh! I cannot square haha!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [10]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
funny_add(1, 2, 3)

321

In [13]:
funny_add(c=3, b=2, a=1)

321

In [ ]:
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

In [15]:
funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

SyntaxError: positional argument follows keyword argument (25483117.py, line 1)

### 2.2 Docstrings

In [16]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

In [17]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [18]:
def my_function(angle, trig_function): # Not def my_function(angle, trig_function())
        print(trig_function(angle))

my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0



1.0
6.123233995736766e-17
-1.0


### 2.4 More unpacking

In [19]:
x, y, z = [1, 2, 3]
print(x, y, z)


1 2 3


In [20]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


## Exercise 1 :  A better calculator I

In [1]:
import numpy as np
def add(x, y):
    return x+y
def subtract(x, y):
    return x-y
def multiply(x, y):
    return x*y
def divide(x, y):
    y = np.array(y)
    assert y.all(), f"{y} is not a valid denominator"
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

print(divide(7, 0))





[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


AssertionError: 0 is not a valid denominator

## Exercise 2 :  A better calculator II

In [1]:
import numpy as np
def add(x, y):
    return x+y
def subtract(x, y):
    return x-y
def multiply(x, y):
    return x*y
def divide(x, y):
    try:
        y = np.array(y)
        if y.all(): #or if (y==0).any()
            return (x/y) 
        else: raise ZeroDivisionError 
    except:
        return (f'{x}/{y} cannot be divided')

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 7])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

print(divide(7, 0))

[100 100 100 100  34]
[-28 -32 -12  52  20]
[2304 2244 2464 1824  189]
[0.5625     0.51515152 0.78571429 3.16666667 3.85714286]
7/0 cannot be divided


In [ ]:
# another way of raising error
# def divide(x, y):
#     y = np.array(y)
#     if y.all():
#         return (x/y) 
#     else: 
#         raise ZeroDivisionError("Did you forget your primary school math? Denominator cannot be zero!") 

In [2]:
x = np.array([5,7,2])
y = np.array([0,0,0])
divide(x, y)

'[5 7 2]/[0 0 0] cannot be divided'