<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

In [1]:
import numpy as np

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting("Super Man")
greeting(name = "Super Man")

'Hello Super Man!'

In [3]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [4]:
print(greeting(name='Super Man'))

Hello Super Man!


In [5]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
list_min, list_max, list_mean

(1, 5, 3.0)

### 1.2 Named functions that don’t return

In [6]:

# Your code here


### 1.3 Anonymous functions

In [7]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

'Hello Super Man!'

In [8]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [9]:
sorted(numbers, key=lambda x:x[0])

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [10]:
def a(x):
    return x[1]

In [11]:
sorted(numbers, key=a)     # Sort by comparing a custom key                               # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [12]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [13]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [14]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting()

'Hello no one!'

In [15]:
def greeting(name=''):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting()

'Hello !'

In [16]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

abstraction: hiding necessary details
reusability: no need to copy and paste everytime
maintainability: change one change all


### 2.2 A word of caution

"I have seen instances where functions are abused; for example, by trying to do too much or having too many arguments. They can also be overused. Having too many functions can make it difficult to read your code and also increase computational overheads. You will get a better feel for when to use functions with experience, but please bear in mind that functions can be misused."

-- [SP2273](https://sps.nus.edu.sg/sp2273/functions-need.html)


## Exercise 1 :  Do you know why?

In [17]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting("Batman")

'Hello Batman! So, nice to meet you!'

When the `if` condition is fulfilled, it has a return value.Python will exit the function with the return value

In [2]:
def greeting(name):
    return 'Hello Batman! So, nice to meet you!'if name == 'Batman' else f'Hello {name}!'

print(greeting('Batman'))
print(greeting(5))

Hello Batman! So, nice to meet you!
Hello 5!


## Exercise 2 :  Calculator functions

In [18]:
import numpy as np
def add(x, y):
    return x+y
def subtract(x, y):
    return x-y
def multiply(x, y):
    return x*y
def divide(x, y):
    y = np.array(y)
    if y.all():
        return x/y
    else: exit()

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

print(divide(7, 0))


[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
None


In [19]:
array = np.array([0, 1, 2])
type(array)

numpy.ndarray

## Exercise 3 :  max_info() with NumPy

In [20]:
def max_info(numbers):
    info = [max(numbers), numbers.index(max(numbers))]
    return info

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

max_info(numbers)

[83, 2]