<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
import numpy as np

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list  
x1 = np_array
print(x[0:4])
print(x[0:6:2])
print(x[5:])
print(x[::-1])

['a1', 'b2', 'c3', 'd4']
['a1', 'c3', 'e5']
['f6', 'g7', 'h8', 'i9', 'j10']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']


### 1.2 Subsetting by masking (Arrays only)

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [4]:
np_array[my_mask] # only true answer
# only works with NumPy arrays

array([ 4,  5,  6,  7,  8,  9, 10])

In [5]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
np_array[~(np_array > 3)]     # '~' means 'NOT'

array([1, 2, 3])

In [7]:
np_array[(np_array > 3) & (np_array < 8)] 
# '&' means 'AND'

array([4, 5, 6, 7])

In [8]:
np_array[(np_array > 3) and (np_array < 8)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
np_array[(np_array < 3) | (np_array > 8)]
# '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [10]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[3]        

[4, 'D']

In [11]:
py_list_2d[3][0]     # returns first element[0] at index 3

4

In [12]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [13]:
py_list_2d[:3][0] # return (py_list_2d[:3])[0]

[1, 'A']

In [14]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [15]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])
np_array_2d[3] 

array(['4', 'D'], dtype='<U11')

In [16]:
np_array_2d[3, 0]   # first element at [3]
                    # uses one pair square bracket, separated by comma

'4'

In [17]:
np_array_2d[3][0]

'4'

In [18]:
np_array_2d[3, 1]   

'D'

In [19]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [20]:
np_array_2d[:3, 0] # return first element of sub-list up to [3]

array(['1', '2', '3'], dtype='<U11')

In [21]:
np_array_2d[:, 0] # return first element of all sub-list

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [22]:
x=[1]*10
x             

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [23]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4] # make sure there's a []
x

[1, 2, 3, 4]

In [24]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [25]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [26]:
x=[1]
x= [2, 3, 4] + x # since the sequence matters
x

[2, 3, 4, 1]

In [27]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [3]:
a=(1, 2, 3)    # tuple uses () instead of [] 
print(a[0])    
a[0] = -1      #tuple is fixed and cannot be changed
a[0] += [10]

1


TypeError: 'tuple' object does not support item assignment

In [6]:
a += 1,   #appending tuple, ',' is recognized as tuple
a

(1, 2, 3, [10], [10], 1)

### 2.2 Be VERY careful when copying

In [29]:
x=[1, 2, 3]
# y=x           # links y and z to x
# z=x           
x=[1, 2, 3]
y=x.copy()      # creates an independent copy
z=x.copy()

## Exercise 1 :  Total recall?

|Term|Brief description|
|:---|:---|
|Subsetting|_Selecting_|
|Indexing|Selecting one element ~~in the list/array by its index~~|
|Slicing|Selecting a range of elements ~~in the list/array by a range indicated by the index~~|
|Masking|Hiding the values in the array that does not fulfill the conditions|


## Exercise 2 :  Show me the ‘odd’ letters

In [30]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
num = np_array_2d [:, 0]
num_odd = num.astype(int)%2
masked_array = np_array_2d[num.astype(bool)]
masked_array [:, 1]


array(['A', 'C', 'B', 'D', 'E', 'G', 'F', 'H', 'J', 'I'], dtype='<U11')