<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(py_super_names[1] == np_super_names[1])

True


In [2]:
np.array([1,2,3])

array([1, 2, 3])

### 1.2 Accessing data from a list (or array)

In [3]:
print(py_super_names[1])
print(np_super_names[1])
print(py_super_names[1] == np_super_names[1])

print(py_super_names[2])
print(py_super_names[-1])
# zero-based index

Iron Man
Iron Man
True
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])
print(superhero_info.keys())
print(list(superhero_info.keys()))
print(list(superhero_info.keys())[1])

Black Widow
dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']
Tony Stark


### 1.4 Higher dimensional lists

In [5]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
print(py_superhero_info[1])

['Tony Stark', 'Iron Man']


## 2 Lists vs. Arrays

### 2.1 Size

In [6]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [7]:
len(py_list_2d)

10

In [8]:
len(np_array_2d)

10

In [9]:
np_array_2d.shape

(10, 2)

In [10]:
py_list_2d.shape

AttributeError: 'list' object has no attribute 'shape'

### 2.2 Arrays are fussy about type

In [12]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
print(np_array + 10)
py_list.append(7)
print(py_list)



[11 12 13 14 15]
[1, 2, 3, 4, 5, 7]


### 2.4 Adding another list

In [14]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [15]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [17]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [31]:
test_list = [1, 'a']
test_list*2

[1, 'a', 1, 'a']

In [18]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [34]:
test_array = np.array(['a','b'])
test_array*2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int32')) -> None

### 2.6 Squaring

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)


In [36]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [37]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [38]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [41]:
py_list == 3     # Does not show if list contains value

False

In [43]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [42]:
len(py_list) == 5

True

In [44]:
np_array == 3  

array([False, False,  True, False, False])

In [45]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

`list: action(list_name)` <br>
`array: array_name.action()`

In [2]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
test_list = ['a', 'b', 'c']
test_array = np.array(test_list)


In [3]:
print(sum(py_list))
print(sum(test_list)) # cannot sum alphabets

15


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [57]:
print(max(py_list))
print(max(test_list)) # evaluates based on the represented number

5
c


In [58]:
min(py_list)

1

In [59]:
np_array.sum()

15

In [60]:
np_array.mean()

3.0

In [62]:
np_array.max()

5

In [63]:
np_array.min()

1

## Exercise 1 :  Total recall?

1. 1. Both can be indexed
   1. Both can be 
1. 1. List are built-in for python, array requires numpy to be imported
   1. List can contain different data types, Array cannot
1. A dictionary is data stored with a key and its corresponding value _separated by a :_



## Exercise 2 :  Index me

In [67]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
i = 0
while i < len(py_list):
    print(py_list[i])
    i += 2
    
#print(py_list[8])   


a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [80]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info)




{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [83]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
num_array = np.array(numbers)
num_array = (num_array == 1)
print(num_array.sum())


9
